### ISSUE TITLE
debian bullseye and other modern distros do not contain `libappindicator1`

### ISSUE THREAD

**Issue by theofficialgman** [alienzhangyw/BlockPi#14]
GTK2 and all its libraries are deprecated and some have already actively been removed in debian bullseye and other debian derivatives.
BlockPi does NOT install on its intended system (anything running pure debian bullseye like the official piOS bullseye 64bit).

How much of the codebase of this application is dependent on this dependency `libappindicator1` and can it be removed?

**Comment by alienzhangyw** [comment]
https://www.electron.build/configuration/linux#debian-package-options
Electron needed them to run on Linux. But since it's deprecated, maybe I should update electron version and remove libappindicator1 from deps.

**Comment by alienzhangyw** [comment]
Try [V1.2.1](https://github.com/alienzhangyw/BlockPi/releases/tag/v1.2.1)
