### ISSUE TITLE
python3-camera was deprecated and removed in bookworm

### ISSUE THREAD

**Issue by theofficialgman** [alienzhangyw/BlockPi#15]
pycamera was deprecated and now removed in piOS bookworm.
You need to support pycamera2 instead which is supported on piOS bullseye and later.

**Comment by alienzhangyw** [comment]
I will try pycamera2.
It seems that there is no migration guide. https://github.com/raspberrypi/picamera2/issues/5
I will try when I'm not busy, but I do not promise everything works fine with pycamera2.

**Comment by alienzhangyw** [comment]
Not supported
